ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

USR_LIB_PATH = /home/$(USER)/Arduino/libraries
#USER_LIB_PATH = /usr/share/arduino/lib
BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk

